Byte decode error
Kerollmops/heed pull request #89
Opened 2020-12-31 00:47 UTC by MarinPostma

2021-01-02 16:24 UTC, Kerollmops requested changes
Thank you, I tried but haven't finished yet. So, you take the lead and I will accept your PR!

----

I am wondering if introducing a custom Result type named `CodecResult`, could be better.
```
type CodecResult<T> = Result<T, Box<dyn Error>>;
```

2021-01-02 16:24 UTC, Kerollmops commented on heed-types/src/cow_slice.rs
> +                Err("The provided bytes do not satisfy the alignment requirements.")?
When I switch from zerocopy to bytemuck I will change this error string into [a nicer error, more precise](https://docs.rs/bytemuck/1.4.1/bytemuck/enum.PodCastError.html)!

2021-01-02 16:24 UTC, Kerollmops commented on heed-types/src/lib.rs
> +    fn bytes_decode(_bytes: &[u8]) -> Result<Self::DItem, Box<dyn std::error::Error>> {
```suggestion
    fn bytes_decode(_bytes: &[u8]) -> Result<Self::DItem, Box<dyn Error>> {
```

By importing the Error trait into the scope.

2021-01-02 16:24 UTC, Kerollmops commented on heed/src/db/polymorph.rs
> +        let key_bytes: Cow<[u8]> = KC::bytes_encode(&key).map_err(|e| Error::Encoding(e))?;
```suggestion
        let key_bytes: Cow<[u8]> = KC::bytes_encode(&key).map_err(Error::Encoding)?;
```

2021-01-02 16:24 UTC, Kerollmops commented on heed/src/lib.rs
> +    Decoding(Box<dyn std::error::Error>),
```suggestion
    Encoding(Box<dyn Error>),
    Decoding(Box<dyn Error>),
```

2021-01-03 16:00 UTC, MarinPostma commented
> I am wondering if introducing a custom public Result type named CodecResult, could be better.

Why not exposing an anyhow Result instead?

2021-01-03 16:08 UTC, Kerollmops commented
> Why not exposing an anyhow Result instead?

I don't want to bring one more dependency in this crate, don't want to force users to use anyhow, and anyhow has been design to be used by binary crates.

Exposing a type alias will work just fine :)

2021-01-28 14:00 UTC, closed without merging